language: ruby
rvm:
  - 2.1.4
env:
  global:
    # created using `travis encrypt -r graphitefriction/graphitefriction.com`
    # GIT_N=<git name> GIT_E=<git email> GH_T=<github oauth token>
    - secure: B5+AgGtknBr8Fgs2QeElkkRALZTX5l3GB8c0CqeW2HNfIj4hzBp6c3gs8rrejJQkiDrw5cuo48vKmsVdHtgcZ5r4sw9hKP5JuuKfFNt3sIbzPsjs453tmFQUKaebGr9NvGymWDB5/WcWZiVEGY4Lu9Y5+NXDnyNztSZsEksK1W4=
branches:
  only:
    - master
script: rake travis
