title: Graphite Friction
author: Sarah White
#blog_path: /blog
blog_path:
local_tz: America/Denver
disqus: graphitefriction
disqus_generate_id: true
disqus_developer: true
haml:
  :ugly: true
asciidoctor:
  :compact: true
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-'
# if no profile is specified, the first with a deploy config is selected
profiles:
  development:
    deploy:
      dummy:
  production:
    base_url: http://graphitefriction.com
    disqus_developer: false
    google_analytics: UA-33133481-1
    # TODO enable once not dependent on system binaries
    #minify: true
    deploy:
      host: github_pages
      branch: master
