title: Graphite Friction
author: Sarah White
#blog_path: /blog
blog_path:
local_tz: America/Denver
disqus: graphitefriction
disqus_generate_id: true
disqus_developer: true
haml:
  :ugly: true
asciidoctor:
  :safe: safe
  :base_dir: null
  :attributes:
    compat-mode: '@'
    idprefix: ''
    idseparator: '-'
# if no profile is specified, the first with a deploy config is selected
profiles:
  development:
    deploy: nil
    #show_drafts: false
  production:
    base_url: http://graphitefriction.com
    disqus_developer: false
    google_analytics_account: UA-33133481-1
    google_analytics:
      account: UA-33133481-1
    scss:
      :line_numbers: false
      :style: :compressed
    #compass_output_style: compressed
    # TODO enable minify once we verify it's working as expected
    #minify: true
    deploy:
      host: github_pages
      branch: gh-pages
